"""estrategias guardadas y su historial de backtests

Revision ID: 1ea33b72d824
Revises: cfc11bc5089e
Create Date: 2026-07-25 16:47:25.423513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ea33b72d824'
down_revision: Union[str, Sequence[str], None] = 'cfc11bc5089e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('strategy_type', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('symbols', sa.JSON(), nullable=False),
    sa.Column('timeframes', sa.JSON(), nullable=False),
    sa.Column('entry_conditions', sa.Text(), nullable=False),
    sa.Column('exit_conditions', sa.Text(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('saved_strategies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_strategies_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_strategies_user_id'), ['user_id'], unique=False)

    op.create_table('strategy_backtest_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('dataset', sa.String(length=120), nullable=False),
    sa.Column('config_snapshot', sa.JSON(), nullable=False),
    sa.Column('initial_equity', sa.Float(), nullable=False),
    sa.Column('num_trades', sa.Integer(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('equity_curve', sa.JSON(), nullable=False),
    sa.Column('trades', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['saved_strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('strategy_backtest_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategy_backtest_runs_strategy_id'), ['strategy_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategy_backtest_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategy_backtest_runs_strategy_id'))

    op.drop_table('strategy_backtest_runs')
    with op.batch_alter_table('saved_strategies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_strategies_user_id'))
        batch_op.drop_index(batch_op.f('ix_saved_strategies_status'))

    op.drop_table('saved_strategies')
    # ### end Alembic commands ###
