"""gestion de riesgo: tope de exposicion abierta por activo y por estrategia

Revision ID: cbb7e8d5fc39
Revises: e14c5399e1df
Create Date: 2026-07-26 21:40:51.671881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbb7e8d5fc39'
down_revision: Union[str, Sequence[str], None] = 'e14c5399e1df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_exposure_per_asset_usdt', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('max_exposure_per_strategy_usdt', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('max_exposure_per_strategy_usdt')
        batch_op.drop_column('max_exposure_per_asset_usdt')

    # ### end Alembic commands ###
